export type Project = {
  id: string;
  slug: string;
  name: string;
  location: string;
  year: string;
  category: "Industrial" | "Apartments" | "Residential Bungalows" | "Commercial" | "Healthcare" | "Institutional" | "Hospitality" | "Interiors";
  tags: string[];
  color: string;
  image?: string;
  images?: string[];
  builtUp?: string;
  description?: string;
  paragraphs?: string[];
};

export const projects: Project[] = [
  {
    id: "01",
    slug: "raj-crest",
    name: "Raj Crest",
    location: "Nashik, India",
    year: "2019",
    category: "Apartments",
    tags: ["Apartment", "Nashik"],
    color: "#b9c0b4",
    image: "/projects/apartments/raj-crest/01.jpg",
    images: [
      "/projects/apartments/raj-crest/01.jpg",
      "/projects/apartments/raj-crest/02.jpg",
      "/projects/apartments/raj-crest/03.jpg",
      "/projects/apartments/raj-crest/04.png",
    ],
    builtUp: "13,355 sqm",
    paragraphs: [
      "Raj Crest is a 13,355 sqm residential development in Nashik, completed in 2019, conceived as a community shaped as much by shared life as by private dwelling. Geometry and proportion set the underlying order — a grid disciplined enough to organise many households, flexible enough to let each unit find its own orientation. Every unit was designed to catch daylight and air on at least two sides, a small discipline that changes how a home feels through the day.",
      "The ground floor was treated as the building's most public room — a threshold between the street and the private life above it. It reflects the studio's continuing pursuit of sense, sensibility, and space — order, depth, and life, brought together in one address.",
    ],
  },
  {
    id: "02",
    slug: "shankar-nagar",
    name: "Shankar Nagar",
    location: "Nashik, India",
    year: "2022",
    category: "Apartments",
    tags: ["Apartment", "Nashik"],
    color: "#bcc2c9",
    image: "/projects/apartments/shankar-nagar/01.jpg",
    images: [
      "/projects/apartments/shankar-nagar/01.jpg",
      "/projects/apartments/shankar-nagar/02.jpg",
      "/projects/apartments/shankar-nagar/03.jpg",
      "/projects/apartments/shankar-nagar/04.jpg",
      "/projects/apartments/shankar-nagar/05.png",
      "/projects/apartments/shankar-nagar/06.png",
    ],
    builtUp: "27,599 sqm",
    paragraphs: [
      "In Nashik, Shankar Nagar brings together 27,599 sqm of residential space, completed in 2022, organised around the everyday rhythms of the families who call it home. The massing steps and folds in response to the site's edges, turning setbacks and orientation requirements into the building's defining geometry rather than its compromise. Balcony depth, window proportion, and material texture were treated as amenities in themselves, not afterthoughts to the plan.",
      "Circulation is generous enough to function as informal gathering space, encouraging the everyday exchange that makes a building feel inhabited rather than occupied. Like all our work, it is built on the belief that architecture should be inhabited, not merely occupied.",
    ],
  },
  {
    id: "03",
    slug: "raj-tower",
    name: "Raj Tower",
    location: "Nashik, India",
    year: "2017",
    category: "Apartments",
    tags: ["Apartment", "Nashik"],
    color: "#c9b9ae",
    image: "/projects/apartments/raj-tower/01.jpg",
    images: [
      "/projects/apartments/raj-tower/01.jpg",
      "/projects/apartments/raj-tower/02.jpg",
      "/projects/apartments/raj-tower/03.jpg",
      "/projects/apartments/raj-tower/04.png",
      "/projects/apartments/raj-tower/05.png",
    ],
    builtUp: "8,776 sqm",
    paragraphs: [
      "Raj Tower, completed in 2017 in Nashik, spans 8,776 sqm — a scale that asked us to design not just units, but a shared address. A considered grid and a clear structural logic give the building its order, so that scale never tips into anonymity. Light and ventilation were treated as design drivers from the earliest massing studies, not resolved later at the window-schedule stage.",
      "Each unit opens toward light and outlook wherever the site allowed, so residents experience the building through daily moments of arrival and pause, not just square footage. The result is a project that measures itself not only by how it looks, but by how it is lived in.",
    ],
  },
  {
    id: "04",
    slug: "ambar-arcade",
    name: "Ambar Arcade",
    location: "Nashik, India",
    year: "2026",
    category: "Apartments",
    tags: ["Apartment", "Nashik"],
    color: "#b8c7c9",
    image: "/projects/apartments/ambar-arcade/01.jpg",
    images: [
      "/projects/apartments/ambar-arcade/01.jpg",
      "/projects/apartments/ambar-arcade/02.jpg",
      "/projects/apartments/ambar-arcade/03.png",
      "/projects/apartments/ambar-arcade/04.png",
    ],
    builtUp: "7,772 sqm",
    paragraphs: [
      "Set in Nashik and completed in 2026, Ambar Arcade is a 7,772 sqm apartment community built on a simple premise: that density need not come at the cost of light, air, or privacy. Facade rhythm and unit geometry were resolved together, so structure and elevation read as one decision rather than two. Balconies, fenestration, and material choices were tuned to bring light and cross-ventilation into every unit, not just the corner ones.",
      "The building's shared spaces were given the same attention as its private ones, on the belief that a home begins at the gate, not the front door. For us, it is one more attempt to bring sense and sensibility into balance — structure with clarity, material with warmth.",
    ],
  },
  {
    id: "05",
    slug: "pandav-enclave",
    name: "Pandav Enclave",
    location: "Nashik, India",
    year: "2021",
    category: "Apartments",
    tags: ["Apartment", "Nashik"],
    color: "#c2bcc9",
    image: "/projects/apartments/pandav-enclave/01.jpg",
    images: [
      "/projects/apartments/pandav-enclave/01.jpg",
      "/projects/apartments/pandav-enclave/02.jpg",
      "/projects/apartments/pandav-enclave/03.jpg",
      "/projects/apartments/pandav-enclave/04.jpg",
      "/projects/apartments/pandav-enclave/05.png",
      "/projects/apartments/pandav-enclave/06.png",
    ],
    builtUp: "8,846 sqm",
    paragraphs: [
      "Pandav Enclave occupies 8,846 sqm in Nashik, completed in 2021, and was designed as a vertical neighbourhood rather than a stack of identical units. Orientation, massing, and structural grid were worked out together from the first sketch, so the building's order comes from its logic rather than applied decoration. Material and colour were kept restrained, so the building ages by weathering honestly rather than by looking dated.",
      "Entrances, staircases, and common areas were designed as places to pause and meet, not just corridors between a unit and the street. It stands as part of MJ Architects' ongoing exploration of how sense, sensibility, and space come together in the built environment.",
    ],
  },
  {
    id: "06",
    slug: "prathmesh-park",
    name: "Prathmesh Park",
    location: "Nashik, India",
    year: "2019",
    category: "Apartments",
    tags: ["Apartment", "Nashik"],
    color: "#c9c4b6",
    image: "/projects/apartments/prathmesh-park/01.jpg",
    images: [
      "/projects/apartments/prathmesh-park/01.jpg",
      "/projects/apartments/prathmesh-park/02.jpg",
      "/projects/apartments/prathmesh-park/03.jpg",
      "/projects/apartments/prathmesh-park/04.png",
      "/projects/apartments/prathmesh-park/05.png",
    ],
    builtUp: "7,977 sqm",
    paragraphs: [
      "Completed in 2019, Prathmesh Park is a 7,977 sqm residential project in Nashik that treats scale as a question of community, not just capacity. Geometry and proportion set the underlying order — a grid disciplined enough to organise many households, flexible enough to let each unit find its own orientation. Every unit was designed to catch daylight and air on at least two sides, a small discipline that changes how a home feels through the day.",
      "The ground floor was treated as the building's most public room — a threshold between the street and the private life above it. In the end, it is measured less by its elevation than by how naturally it has been taken up by the people who use it.",
    ],
  },
  {
    id: "07",
    slug: "mhada-satpur",
    name: "Mhada Satpur",
    location: "Nashik, India",
    year: "2024",
    category: "Apartments",
    tags: ["Apartment", "Nashik"],
    color: "#b9c0b4",
    image: "/projects/apartments/mhada-satpur/01.jpg",
    images: [
      "/projects/apartments/mhada-satpur/01.jpg",
      "/projects/apartments/mhada-satpur/02.jpg",
      "/projects/apartments/mhada-satpur/03.png",
      "/projects/apartments/mhada-satpur/04.png",
    ],
    builtUp: "4,953 sqm",
    paragraphs: [
      "Mhada Satpur is a 4,953 sqm residential development in Nashik, completed in 2024, conceived as a community shaped as much by shared life as by private dwelling. The massing steps and folds in response to the site's edges, turning setbacks and orientation requirements into the building's defining geometry rather than its compromise. Balcony depth, window proportion, and material texture were treated as amenities in themselves, not afterthoughts to the plan.",
      "Circulation is generous enough to function as informal gathering space, encouraging the everyday exchange that makes a building feel inhabited rather than occupied. It reflects the studio's continuing pursuit of sense, sensibility, and space — order, depth, and life, brought together in one address.",
    ],
  },
  {
    id: "08",
    slug: "cosmos-chember",
    name: "Cosmos Chember",
    location: "Nashik, India",
    year: "2026",
    category: "Apartments",
    tags: ["Apartment", "Nashik"],
    color: "#bcc2c9",
    image: "/projects/apartments/cosmos-chember/01.jpg",
    images: [
      "/projects/apartments/cosmos-chember/01.jpg",
      "/projects/apartments/cosmos-chember/02.png",
      "/projects/apartments/cosmos-chember/03.png",
    ],
    builtUp: "7,473 sqm",
    paragraphs: [
      "In Nashik, Cosmos Chember brings together 7,473 sqm of residential space, completed in 2026, organised around the everyday rhythms of the families who call it home. A considered grid and a clear structural logic give the building its order, so that scale never tips into anonymity. Light and ventilation were treated as design drivers from the earliest massing studies, not resolved later at the window-schedule stage.",
      "Each unit opens toward light and outlook wherever the site allowed, so residents experience the building through daily moments of arrival and pause, not just square footage. Like all our work, it is built on the belief that architecture should be inhabited, not merely occupied.",
    ],
  },
  {
    id: "09",
    slug: "vintage-valley",
    name: "Vintage Valley",
    location: "Igatpuri, India",
    year: "2024",
    category: "Apartments",
    tags: ["Apartment", "Igatpuri"],
    color: "#c9b9ae",
    image: "/projects/apartments/vintage-valley/01.jpg",
    images: [
      "/projects/apartments/vintage-valley/01.jpg",
      "/projects/apartments/vintage-valley/02.jpg",
      "/projects/apartments/vintage-valley/03.png",
      "/projects/apartments/vintage-valley/04.png",
      "/projects/apartments/vintage-valley/05.png",
    ],
    builtUp: "6,985 sqm",
    paragraphs: [
      "Vintage Valley, completed in 2024 in Igatpuri, spans 6,985 sqm — a scale that asked us to design not just units, but a shared address. Facade rhythm and unit geometry were resolved together, so structure and elevation read as one decision rather than two. Balconies, fenestration, and material choices were tuned to bring light and cross-ventilation into every unit, not just the corner ones.",
      "The building's shared spaces were given the same attention as its private ones, on the belief that a home begins at the gate, not the front door. The result is a project that measures itself not only by how it looks, but by how it is lived in.",
    ],
  },
  {
    id: "10",
    slug: "krishnai-galaxy",
    name: "Krishnai Galaxy",
    location: "Nashik, India",
    year: "2019",
    category: "Apartments",
    tags: ["Apartment", "Nashik"],
    color: "#b8c7c9",
    image: "/projects/apartments/krishnai-galaxy/01.jpg",
    images: [
      "/projects/apartments/krishnai-galaxy/01.jpg",
      "/projects/apartments/krishnai-galaxy/02.jpg",
      "/projects/apartments/krishnai-galaxy/03.jpg",
      "/projects/apartments/krishnai-galaxy/04.png",
    ],
    builtUp: "3,847 sqm",
    paragraphs: [
      "Set in Nashik and completed in 2019, Krishnai Galaxy is a 3,847 sqm apartment community built on a simple premise: that density need not come at the cost of light, air, or privacy. Orientation, massing, and structural grid were worked out together from the first sketch, so the building's order comes from its logic rather than applied decoration. Material and colour were kept restrained, so the building ages by weathering honestly rather than by looking dated.",
      "Entrances, staircases, and common areas were designed as places to pause and meet, not just corridors between a unit and the street. For us, it is one more attempt to bring sense and sensibility into balance — structure with clarity, material with warmth.",
    ],
  },
  {
    id: "11",
    slug: "natures-pride",
    name: "Nature's Pride",
    location: "Nashik, India",
    year: "2024",
    category: "Apartments",
    tags: ["Apartment", "Nashik"],
    color: "#c2bcc9",
    image: "/projects/apartments/natures-pride/01.jpg",
    images: [
      "/projects/apartments/natures-pride/01.jpg",
      "/projects/apartments/natures-pride/02.jpg",
      "/projects/apartments/natures-pride/03.png",
      "/projects/apartments/natures-pride/04.png",
    ],
    builtUp: "2,249 sqm",
    paragraphs: [
      "Nature's Pride occupies 2,249 sqm in Nashik, completed in 2024, and was designed as a vertical neighbourhood rather than a stack of identical units. Geometry and proportion set the underlying order — a grid disciplined enough to organise many households, flexible enough to let each unit find its own orientation. Every unit was designed to catch daylight and air on at least two sides, a small discipline that changes how a home feels through the day.",
      "The ground floor was treated as the building's most public room — a threshold between the street and the private life above it. It stands as part of MJ Architects' ongoing exploration of how sense, sensibility, and space come together in the built environment.",
    ],
  },
  {
    id: "12",
    slug: "indu-park",
    name: "Indu Park",
    location: "Nashik, India",
    year: "2026",
    category: "Apartments",
    tags: ["Apartment", "Nashik"],
    color: "#c9c4b6",
    image: "/projects/apartments/indu-park/01.jpg",
    images: [
      "/projects/apartments/indu-park/01.jpg",
      "/projects/apartments/indu-park/02.png",
      "/projects/apartments/indu-park/03.png",
    ],
    builtUp: "2,175 sqm",
    paragraphs: [
      "Completed in 2026, Indu Park is a 2,175 sqm residential project in Nashik that treats scale as a question of community, not just capacity. The massing steps and folds in response to the site's edges, turning setbacks and orientation requirements into the building's defining geometry rather than its compromise. Balcony depth, window proportion, and material texture were treated as amenities in themselves, not afterthoughts to the plan.",
      "Circulation is generous enough to function as informal gathering space, encouraging the everyday exchange that makes a building feel inhabited rather than occupied. In the end, it is measured less by its elevation than by how naturally it has been taken up by the people who use it.",
    ],
  },
  {
    id: "13",
    slug: "shri-ravi-enclave",
    name: "Shri Ravi Enclave",
    location: "Nashik, India",
    year: "2013",
    category: "Apartments",
    tags: ["Apartment", "Nashik"],
    color: "#b9c0b4",
    image: "/projects/apartments/shri-ravi-enclave/01.jpg",
    images: [
      "/projects/apartments/shri-ravi-enclave/01.jpg",
      "/projects/apartments/shri-ravi-enclave/02.jpg",
      "/projects/apartments/shri-ravi-enclave/03.jpg",
      "/projects/apartments/shri-ravi-enclave/04.png",
    ],
    builtUp: "4,849 sqm",
    paragraphs: [
      "Shri Ravi Enclave is a 4,849 sqm residential development in Nashik, completed in 2013, conceived as a community shaped as much by shared life as by private dwelling. A considered grid and a clear structural logic give the building its order, so that scale never tips into anonymity. Light and ventilation were treated as design drivers from the earliest massing studies, not resolved later at the window-schedule stage.",
      "Each unit opens toward light and outlook wherever the site allowed, so residents experience the building through daily moments of arrival and pause, not just square footage. It reflects the studio's continuing pursuit of sense, sensibility, and space — order, depth, and life, brought together in one address.",
    ],
  },
  {
    id: "14",
    slug: "aakar-beyond",
    name: "Aakar Beyond",
    location: "Nashik, India",
    year: "2018",
    category: "Apartments",
    tags: ["Apartment", "Nashik"],
    color: "#bcc2c9",
    image: "/projects/apartments/aakar-beyond/01.jpg",
    images: [
      "/projects/apartments/aakar-beyond/01.jpg",
      "/projects/apartments/aakar-beyond/02.jpg",
      "/projects/apartments/aakar-beyond/03.jpg",
      "/projects/apartments/aakar-beyond/04.png",
      "/projects/apartments/aakar-beyond/05.png",
    ],
    builtUp: "2,481 sqm",
    paragraphs: [
      "In Nashik, Aakar Beyond brings together 2,481 sqm of residential space, completed in 2018, organised around the everyday rhythms of the families who call it home. Facade rhythm and unit geometry were resolved together, so structure and elevation read as one decision rather than two. Balconies, fenestration, and material choices were tuned to bring light and cross-ventilation into every unit, not just the corner ones.",
      "The building's shared spaces were given the same attention as its private ones, on the belief that a home begins at the gate, not the front door. Like all our work, it is built on the belief that architecture should be inhabited, not merely occupied.",
    ],
  },
  {
    id: "15",
    slug: "parkside-palms",
    name: "Parkside Palms",
    location: "Nashik, India",
    year: "2026",
    category: "Apartments",
    tags: ["Apartment", "Nashik"],
    color: "#c9b9ae",
    image: "/projects/apartments/parkside-palms/01.jpg",
    images: [
      "/projects/apartments/parkside-palms/01.jpg",
      "/projects/apartments/parkside-palms/02.png",
      "/projects/apartments/parkside-palms/03.png",
    ],
    builtUp: "3,109 sqm",
    paragraphs: [
      "Parkside Palms, completed in 2026 in Nashik, spans 3,109 sqm — a scale that asked us to design not just units, but a shared address. Orientation, massing, and structural grid were worked out together from the first sketch, so the building's order comes from its logic rather than applied decoration. Material and colour were kept restrained, so the building ages by weathering honestly rather than by looking dated.",
      "Entrances, staircases, and common areas were designed as places to pause and meet, not just corridors between a unit and the street. The result is a project that measures itself not only by how it looks, but by how it is lived in.",
    ],
  },
  {
    id: "16",
    slug: "paramkaruna-apartment",
    name: "Paramkaruna Apartment",
    location: "Nashik, India",
    year: "2026",
    category: "Apartments",
    tags: ["Apartment", "Nashik"],
    color: "#b8c7c9",
    image: "/projects/apartments/paramkaruna-apartment/01.jpg",
    images: [
      "/projects/apartments/paramkaruna-apartment/01.jpg",
      "/projects/apartments/paramkaruna-apartment/02.png",
      "/projects/apartments/paramkaruna-apartment/03.png",
    ],
    builtUp: "1,051 sqm",
    paragraphs: [
      "Set in Nashik and completed in 2026, Paramkaruna Apartment is a 1,051 sqm apartment community built on a simple premise: that density need not come at the cost of light, air, or privacy. Geometry and proportion set the underlying order — a grid disciplined enough to organise many households, flexible enough to let each unit find its own orientation. Every unit was designed to catch daylight and air on at least two sides, a small discipline that changes how a home feels through the day.",
      "The ground floor was treated as the building's most public room — a threshold between the street and the private life above it. For us, it is one more attempt to bring sense and sensibility into balance — structure with clarity, material with warmth.",
    ],
  },
  {
    id: "17",
    slug: "garden-view-apartment",
    name: "Garden View Apartment",
    location: "Nashik, India",
    year: "2025",
    category: "Apartments",
    tags: ["Apartment", "Nashik"],
    color: "#c2bcc9",
    image: "/projects/apartments/garden-view-apartment/01.jpg",
    images: [
      "/projects/apartments/garden-view-apartment/01.jpg",
      "/projects/apartments/garden-view-apartment/02.jpg",
      "/projects/apartments/garden-view-apartment/03.png",
      "/projects/apartments/garden-view-apartment/04.png",
    ],
    builtUp: "1,065 sqm",
    paragraphs: [
      "Garden View Apartment occupies 1,065 sqm in Nashik, completed in 2025, and was designed as a vertical neighbourhood rather than a stack of identical units. The massing steps and folds in response to the site's edges, turning setbacks and orientation requirements into the building's defining geometry rather than its compromise. Balcony depth, window proportion, and material texture were treated as amenities in themselves, not afterthoughts to the plan.",
      "Circulation is generous enough to function as informal gathering space, encouraging the everyday exchange that makes a building feel inhabited rather than occupied. It stands as part of MJ Architects' ongoing exploration of how sense, sensibility, and space come together in the built environment.",
    ],
  },
  {
    id: "18",
    slug: "rukmini-park",
    name: "Rukmini Park",
    location: "Nashik, India",
    year: "2020",
    category: "Apartments",
    tags: ["Apartment", "Nashik"],
    color: "#c9c4b6",
    image: "/projects/apartments/rukmini-park/01.jpg",
    images: [
      "/projects/apartments/rukmini-park/01.jpg",
      "/projects/apartments/rukmini-park/02.png",
      "/projects/apartments/rukmini-park/03.png",
    ],
    builtUp: "560 sqm",
    paragraphs: [
      "Completed in 2020, Rukmini Park is a 560 sqm residential project in Nashik that treats scale as a question of community, not just capacity. A considered grid and a clear structural logic give the building its order, so that scale never tips into anonymity. Light and ventilation were treated as design drivers from the earliest massing studies, not resolved later at the window-schedule stage.",
      "Each unit opens toward light and outlook wherever the site allowed, so residents experience the building through daily moments of arrival and pause, not just square footage. In the end, it is measured less by its elevation than by how naturally it has been taken up by the people who use it.",
    ],
  },
  {
    id: "19",
    slug: "shrishti-pandhari",
    name: "Shrishti Pandhari",
    location: "Pandharpur, India",
    year: "2015",
    category: "Apartments",
    tags: ["Apartment", "Pandharpur"],
    color: "#b9c0b4",
    image: "/projects/apartments/shrishti-pandhari/01.jpg",
    images: [
      "/projects/apartments/shrishti-pandhari/01.jpg",
      "/projects/apartments/shrishti-pandhari/02.jpg",
      "/projects/apartments/shrishti-pandhari/03.jpg",
      "/projects/apartments/shrishti-pandhari/04.jpg",
      "/projects/apartments/shrishti-pandhari/05.jpg",
    ],
    builtUp: "7,432 sqm",
    paragraphs: [
      "Shrishti Pandhari is a 7,432 sqm residential development in Pandharpur, completed in 2015, conceived as a community shaped as much by shared life as by private dwelling. Facade rhythm and unit geometry were resolved together, so structure and elevation read as one decision rather than two. Balconies, fenestration, and material choices were tuned to bring light and cross-ventilation into every unit, not just the corner ones.",
      "The building's shared spaces were given the same attention as its private ones, on the belief that a home begins at the gate, not the front door. It reflects the studio's continuing pursuit of sense, sensibility, and space — order, depth, and life, brought together in one address.",
    ],
  },
  {
    id: "20",
    slug: "jay-shankar-bungalow",
    name: "Jay Shankar Bungalow",
    location: "Nashik, India",
    year: "2025",
    category: "Residential Bungalows",
    tags: ["Residential Bungalow", "Nashik"],
    color: "#bcc2c9",
    image: "/projects/bungalows/jay-shankar-bungalow/01.jpg",
    images: [
      "/projects/bungalows/jay-shankar-bungalow/01.jpg",
      "/projects/bungalows/jay-shankar-bungalow/02.png",
      "/projects/bungalows/jay-shankar-bungalow/03.png",
    ],
    builtUp: "394 sqm",
    paragraphs: [
      "Jay Shankar Bungalow is a family residence in Nashik, completed in 2025 on a built-up area of 394 sqm, designed around the particular rhythms of the household it was built for. The plan is organised around a clear geometry — rooms sequenced by use and privacy rather than by convention — giving the house an underlying order that is easy to live with. Natural light, material texture, and a restrained palette give the home its character, rather than ornament applied after the fact.",
      "The house is organised to be experienced gradually — arrival, threshold, gathering space, and private room — rather than taken in all at once. For us, it is one more attempt to bring sense and sensibility into balance — structure with clarity, material with warmth.",
    ],
  },
  {
    id: "21",
    slug: "siddheshwar-walekar",
    name: "Siddheshwar Walekar",
    location: "Pimpalgaon, India",
    year: "2026",
    category: "Residential Bungalows",
    tags: ["Residential Bungalow", "Pimpalgaon"],
    color: "#c9b9ae",
    image: "/projects/bungalows/siddheshwar-walekar/01.jpg",
    images: [
      "/projects/bungalows/siddheshwar-walekar/01.jpg",
      "/projects/bungalows/siddheshwar-walekar/02.jpg",
      "/projects/bungalows/siddheshwar-walekar/03.jpg",
      "/projects/bungalows/siddheshwar-walekar/04.png",
      "/projects/bungalows/siddheshwar-walekar/05.png",
      "/projects/bungalows/siddheshwar-walekar/06.png",
    ],
    builtUp: "681 sqm",
    paragraphs: [
      "Completed in 2026 in Pimpalgaon, Siddheshwar Walekar is a 681 sqm home shaped less by a predetermined style than by its site and the family it serves. Structure and proportion were resolved early, so the home's geometry stays legible even as it responds to the specific demands of its site. Openings, courtyards, and material transitions were considered for how they feel underfoot and overhead, not only how they read in a photograph.",
      "Every room was designed with a specific moment of the family's day in mind, from morning light in the kitchen to evening shade on the verandah. It stands as part of MJ Architects' ongoing exploration of how sense, sensibility, and space come together in the built environment.",
    ],
  },
  {
    id: "22",
    slug: "pravin-walekar",
    name: "Pravin Walekar",
    location: "Pimpalgaon, India",
    year: "2026",
    category: "Residential Bungalows",
    tags: ["Residential Bungalow", "Pimpalgaon"],
    color: "#b8c7c9",
    image: "/projects/bungalows/pravin-walekar/01.jpg",
    images: [
      "/projects/bungalows/pravin-walekar/01.jpg",
      "/projects/bungalows/pravin-walekar/02.png",
      "/projects/bungalows/pravin-walekar/03.png",
      "/projects/bungalows/pravin-walekar/04.png",
    ],
    builtUp: "734 sqm",
    paragraphs: [
      "Pravin Walekar, completed in 2026, sits on 734 sqm in Pimpalgaon — a home designed from the inside out, starting with how the family actually lives. A disciplined plan and a considered structural grid give the house its order, freeing the rest of the design to respond to light, material, and everyday use. Material choices favour warmth and durability over display, so the house feels lived-in rather than staged.",
      "The sequence from entry to living spaces to private rooms was designed as a series of thresholds, each marking a shift in privacy and light. In the end, it is measured less by its elevation than by how naturally it has been taken up by the people who use it.",
    ],
  },
  {
    id: "23",
    slug: "shyamji-soni-pipariya",
    name: "Shyamji Soni Pipariya",
    location: "Pipariya, Madhya Pradesh, India",
    year: "2021",
    category: "Residential Bungalows",
    tags: ["Residential Bungalow", "Pipariya, Madhya Pradesh"],
    color: "#c2bcc9",
    image: "/projects/bungalows/shyamji-soni-pipariya/01.jpg",
    images: [
      "/projects/bungalows/shyamji-soni-pipariya/01.jpg",
      "/projects/bungalows/shyamji-soni-pipariya/02.png",
    ],
    builtUp: "1,100 sqm",
    paragraphs: [
      "In Pipariya, Madhya Pradesh, Shyamji Soni Pipariya is a 1,100 sqm residence completed in 2021, conceived as a quiet, considered response to its site and its clients. Orientation and massing were shaped by the site's conditions first — sun path, approach, and neighbouring context — before any room was drawn. Material and light were chosen to age well and feel warm at close range — the qualities a family notices every day, long after a house is finished.",
      "Courtyards, verandahs, and transition spaces give the family room to gather and to withdraw, within the same home. It reflects the studio's continuing pursuit of sense, sensibility, and space — order, depth, and life, brought together in one address.",
    ],
  },
  {
    id: "24",
    slug: "rahul-chaudhari",
    name: "Rahul Chaudhari",
    location: "Shahada, India",
    year: "2018",
    category: "Residential Bungalows",
    tags: ["Residential Bungalow", "Shahada"],
    color: "#c9c4b6",
    image: "/projects/bungalows/rahul-chaudhari/01.jpg",
    images: [
      "/projects/bungalows/rahul-chaudhari/01.jpg",
      "/projects/bungalows/rahul-chaudhari/02.png",
      "/projects/bungalows/rahul-chaudhari/03.png",
    ],
    builtUp: "246 sqm",
    paragraphs: [
      "Rahul Chaudhari occupies 246 sqm in Shahada, completed in 2018, built on the conviction that a family home should be understood before it is designed. The plan is organised around a clear geometry — rooms sequenced by use and privacy rather than by convention — giving the house an underlying order that is easy to live with. Natural light, material texture, and a restrained palette give the home its character, rather than ornament applied after the fact.",
      "The house is organised to be experienced gradually — arrival, threshold, gathering space, and private room — rather than taken in all at once. Like all our work, it is built on the belief that architecture should be inhabited, not merely occupied.",
    ],
  },
  {
    id: "25",
    slug: "deepak-bodhale",
    name: "Deepak Bodhale",
    location: "Makhmalabad, Nashik, India",
    year: "2018",
    category: "Residential Bungalows",
    tags: ["Residential Bungalow", "Makhmalabad, Nashik"],
    color: "#b9c0b4",
    image: "/projects/bungalows/deepak-bodhale/01.jpg",
    images: [
      "/projects/bungalows/deepak-bodhale/01.jpg",
      "/projects/bungalows/deepak-bodhale/02.jpg",
      "/projects/bungalows/deepak-bodhale/03.png",
      "/projects/bungalows/deepak-bodhale/04.png",
      "/projects/bungalows/deepak-bodhale/05.png",
    ],
    builtUp: "349 sqm",
    paragraphs: [
      "Completed in 2018, Deepak Bodhale is a 349 sqm house in Makhmalabad, Nashik that treats the brief — a family's daily life — as the real starting point of the design. Structure and proportion were resolved early, so the home's geometry stays legible even as it responds to the specific demands of its site. Openings, courtyards, and material transitions were considered for how they feel underfoot and overhead, not only how they read in a photograph.",
      "Every room was designed with a specific moment of the family's day in mind, from morning light in the kitchen to evening shade on the verandah. The result is a project that measures itself not only by how it looks, but by how it is lived in.",
    ],
  },
  {
    id: "26",
    slug: "dr-avinash-chaudhari",
    name: "Dr. Avinash Chaudhari",
    location: "Shahada, India",
    year: "2020",
    category: "Residential Bungalows",
    tags: ["Residential Bungalow", "Shahada"],
    color: "#bcc2c9",
    image: "/projects/bungalows/dr-avinash-chaudhari/01.jpg",
    images: [
      "/projects/bungalows/dr-avinash-chaudhari/01.jpg",
      "/projects/bungalows/dr-avinash-chaudhari/02.jpg",
      "/projects/bungalows/dr-avinash-chaudhari/03.jpg",
      "/projects/bungalows/dr-avinash-chaudhari/04.png",
      "/projects/bungalows/dr-avinash-chaudhari/05.png",
      "/projects/bungalows/dr-avinash-chaudhari/06.png",
    ],
    builtUp: "692 sqm",
    paragraphs: [
      "Dr. Avinash Chaudhari is a family residence in Shahada, completed in 2020 on a built-up area of 692 sqm, designed around the particular rhythms of the household it was built for. A disciplined plan and a considered structural grid give the house its order, freeing the rest of the design to respond to light, material, and everyday use. Material choices favour warmth and durability over display, so the house feels lived-in rather than staged.",
      "The sequence from entry to living spaces to private rooms was designed as a series of thresholds, each marking a shift in privacy and light. For us, it is one more attempt to bring sense and sensibility into balance — structure with clarity, material with warmth.",
    ],
  },
  {
    id: "27",
    slug: "sonawane-bungalow",
    name: "Sonawane Bungalow",
    location: "Taloda, Nandurbar, India",
    year: "2018",
    category: "Residential Bungalows",
    tags: ["Residential Bungalow", "Taloda, Nandurbar"],
    color: "#c9b9ae",
    image: "/projects/bungalows/sonawane-bungalow/01.jpg",
    images: [
      "/projects/bungalows/sonawane-bungalow/01.jpg",
      "/projects/bungalows/sonawane-bungalow/02.png",
      "/projects/bungalows/sonawane-bungalow/03.png",
    ],
    builtUp: "386 sqm",
    paragraphs: [
      "Completed in 2018 in Taloda, Nandurbar, Sonawane Bungalow is a 386 sqm home shaped less by a predetermined style than by its site and the family it serves. Orientation and massing were shaped by the site's conditions first — sun path, approach, and neighbouring context — before any room was drawn. Material and light were chosen to age well and feel warm at close range — the qualities a family notices every day, long after a house is finished.",
      "Courtyards, verandahs, and transition spaces give the family room to gather and to withdraw, within the same home. It stands as part of MJ Architects' ongoing exploration of how sense, sensibility, and space come together in the built environment.",
    ],
  },
  {
    id: "28",
    slug: "dharmendra-patel",
    name: "Dharmendra Patel",
    location: "Shahada, India",
    year: "2019",
    category: "Residential Bungalows",
    tags: ["Residential Bungalow", "Shahada"],
    color: "#b8c7c9",
    image: "/projects/bungalows/dharmendra-patel/01.jpg",
    images: [
      "/projects/bungalows/dharmendra-patel/01.jpg",
      "/projects/bungalows/dharmendra-patel/02.jpg",
      "/projects/bungalows/dharmendra-patel/03.png",
      "/projects/bungalows/dharmendra-patel/04.png",
    ],
    builtUp: "355 sqm",
    paragraphs: [
      "Dharmendra Patel, completed in 2019, sits on 355 sqm in Shahada — a home designed from the inside out, starting with how the family actually lives. The plan is organised around a clear geometry — rooms sequenced by use and privacy rather than by convention — giving the house an underlying order that is easy to live with. Natural light, material texture, and a restrained palette give the home its character, rather than ornament applied after the fact.",
      "The house is organised to be experienced gradually — arrival, threshold, gathering space, and private room — rather than taken in all at once. In the end, it is measured less by its elevation than by how naturally it has been taken up by the people who use it.",
    ],
  },
  {
    id: "29",
    slug: "ashok-bodke",
    name: "Ashok Bodke",
    location: "Pethroad, Nashik, India",
    year: "2016",
    category: "Residential Bungalows",
    tags: ["Residential Bungalow", "Pethroad, Nashik"],
    color: "#c2bcc9",
    image: "/projects/bungalows/ashok-bodke/01.jpg",
    images: [
      "/projects/bungalows/ashok-bodke/01.jpg",
      "/projects/bungalows/ashok-bodke/02.jpg",
      "/projects/bungalows/ashok-bodke/03.png",
      "/projects/bungalows/ashok-bodke/04.png",
    ],
    builtUp: "242 sqm",
    paragraphs: [
      "In Pethroad, Nashik, Ashok Bodke is a 242 sqm residence completed in 2016, conceived as a quiet, considered response to its site and its clients. Structure and proportion were resolved early, so the home's geometry stays legible even as it responds to the specific demands of its site. Openings, courtyards, and material transitions were considered for how they feel underfoot and overhead, not only how they read in a photograph.",
      "Every room was designed with a specific moment of the family's day in mind, from morning light in the kitchen to evening shade on the verandah. It reflects the studio's continuing pursuit of sense, sensibility, and space — order, depth, and life, brought together in one address.",
    ],
  },
  {
    id: "30",
    slug: "dr-akshay-patil",
    name: "Dr. Akshay Patil",
    location: "Nashik, India",
    year: "2025",
    category: "Residential Bungalows",
    tags: ["Residential Bungalow", "Nashik"],
    color: "#c9c4b6",
    image: "/projects/bungalows/dr-akshay-patil/01.jpg",
    images: [
      "/projects/bungalows/dr-akshay-patil/01.jpg",
      "/projects/bungalows/dr-akshay-patil/02.png",
      "/projects/bungalows/dr-akshay-patil/03.png",
    ],
    builtUp: "161 sqm",
    paragraphs: [
      "Dr. Akshay Patil occupies 161 sqm in Nashik, completed in 2025, built on the conviction that a family home should be understood before it is designed. A disciplined plan and a considered structural grid give the house its order, freeing the rest of the design to respond to light, material, and everyday use. Material choices favour warmth and durability over display, so the house feels lived-in rather than staged.",
      "The sequence from entry to living spaces to private rooms was designed as a series of thresholds, each marking a shift in privacy and light. Like all our work, it is built on the belief that architecture should be inhabited, not merely occupied.",
    ],
  },
  {
    id: "31",
    slug: "ajay-patil",
    name: "Ajay Patil",
    location: "Nashik, India",
    year: "2021",
    category: "Residential Bungalows",
    tags: ["Residential Bungalow", "Nashik"],
    color: "#b9c0b4",
    image: "/projects/bungalows/ajay-patil/01.jpg",
    images: [
      "/projects/bungalows/ajay-patil/01.jpg",
      "/projects/bungalows/ajay-patil/02.png",
      "/projects/bungalows/ajay-patil/03.png",
    ],
    builtUp: "168 sqm",
    paragraphs: [
      "Completed in 2021, Ajay Patil is a 168 sqm house in Nashik that treats the brief — a family's daily life — as the real starting point of the design. Orientation and massing were shaped by the site's conditions first — sun path, approach, and neighbouring context — before any room was drawn. Material and light were chosen to age well and feel warm at close range — the qualities a family notices every day, long after a house is finished.",
      "Courtyards, verandahs, and transition spaces give the family room to gather and to withdraw, within the same home. The result is a project that measures itself not only by how it looks, but by how it is lived in.",
    ],
  },
  {
    id: "32",
    slug: "dr-chandrakant-patil",
    name: "Dr. Chandrakant Patil",
    location: "Shahada, India",
    year: "2020",
    category: "Residential Bungalows",
    tags: ["Residential Bungalow", "Shahada"],
    color: "#bcc2c9",
    image: "/projects/bungalows/dr-chandrakant-patil/01.jpg",
    images: [
      "/projects/bungalows/dr-chandrakant-patil/01.jpg",
      "/projects/bungalows/dr-chandrakant-patil/02.png",
      "/projects/bungalows/dr-chandrakant-patil/03.png",
    ],
    builtUp: "364 sqm",
    paragraphs: [
      "Dr. Chandrakant Patil is a family residence in Shahada, completed in 2020 on a built-up area of 364 sqm, designed around the particular rhythms of the household it was built for. The plan is organised around a clear geometry — rooms sequenced by use and privacy rather than by convention — giving the house an underlying order that is easy to live with. Natural light, material texture, and a restrained palette give the home its character, rather than ornament applied after the fact.",
      "The house is organised to be experienced gradually — arrival, threshold, gathering space, and private room — rather than taken in all at once. For us, it is one more attempt to bring sense and sensibility into balance — structure with clarity, material with warmth.",
    ],
  },
  {
    id: "33",
    slug: "dr-raj-khule",
    name: "Dr. Raj Khule",
    location: "Taloda, Nandurbar, India",
    year: "2018",
    category: "Residential Bungalows",
    tags: ["Residential Bungalow", "Taloda, Nandurbar"],
    color: "#c9b9ae",
    image: "/projects/bungalows/dr-raj-khule/01.jpg",
    images: [
      "/projects/bungalows/dr-raj-khule/01.jpg",
      "/projects/bungalows/dr-raj-khule/02.png",
      "/projects/bungalows/dr-raj-khule/03.png",
    ],
    builtUp: "260 sqm",
    paragraphs: [
      "Completed in 2018 in Taloda, Nandurbar, Dr. Raj Khule is a 260 sqm home shaped less by a predetermined style than by its site and the family it serves. Structure and proportion were resolved early, so the home's geometry stays legible even as it responds to the specific demands of its site. Openings, courtyards, and material transitions were considered for how they feel underfoot and overhead, not only how they read in a photograph.",
      "Every room was designed with a specific moment of the family's day in mind, from morning light in the kitchen to evening shade on the verandah. It stands as part of MJ Architects' ongoing exploration of how sense, sensibility, and space come together in the built environment.",
    ],
  },
  {
    id: "34",
    slug: "yashaswi-patil",
    name: "Yashaswi Patil",
    location: "Shahada, India",
    year: "2016",
    category: "Residential Bungalows",
    tags: ["Residential Bungalow", "Shahada"],
    color: "#b8c7c9",
    image: "/projects/bungalows/yashaswi-patil/01.jpg",
    images: [
      "/projects/bungalows/yashaswi-patil/01.jpg",
      "/projects/bungalows/yashaswi-patil/02.png",
      "/projects/bungalows/yashaswi-patil/03.png",
    ],
    builtUp: "223 sqm",
    paragraphs: [
      "Yashaswi Patil, completed in 2016, sits on 223 sqm in Shahada — a home designed from the inside out, starting with how the family actually lives. A disciplined plan and a considered structural grid give the house its order, freeing the rest of the design to respond to light, material, and everyday use. Material choices favour warmth and durability over display, so the house feels lived-in rather than staged.",
      "The sequence from entry to living spaces to private rooms was designed as a series of thresholds, each marking a shift in privacy and light. In the end, it is measured less by its elevation than by how naturally it has been taken up by the people who use it.",
    ],
  },
  {
    id: "35",
    slug: "bhagwanbhai-chaudhari",
    name: "Bhagwanbhai Chaudhari",
    location: "Mahswad, Shahada, India",
    year: "2016",
    category: "Residential Bungalows",
    tags: ["Residential Bungalow", "Mahswad, Shahada"],
    color: "#c2bcc9",
    image: "/projects/bungalows/bhagwanbhai-chaudhari/01.jpg",
    images: [
      "/projects/bungalows/bhagwanbhai-chaudhari/01.jpg",
      "/projects/bungalows/bhagwanbhai-chaudhari/02.png",
      "/projects/bungalows/bhagwanbhai-chaudhari/03.png",
    ],
    builtUp: "268 sqm",
    paragraphs: [
      "In Mahswad, Shahada, Bhagwanbhai Chaudhari is a 268 sqm residence completed in 2016, conceived as a quiet, considered response to its site and its clients. Orientation and massing were shaped by the site's conditions first — sun path, approach, and neighbouring context — before any room was drawn. Material and light were chosen to age well and feel warm at close range — the qualities a family notices every day, long after a house is finished.",
      "Courtyards, verandahs, and transition spaces give the family room to gather and to withdraw, within the same home. It reflects the studio's continuing pursuit of sense, sensibility, and space — order, depth, and life, brought together in one address.",
    ],
  },
  {
    id: "36",
    slug: "amol-patil-row-house",
    name: "Amol Patil Row House",
    location: "Nashik, India",
    year: "2023",
    category: "Residential Bungalows",
    tags: ["Residential Bungalow", "Nashik"],
    color: "#c9c4b6",
    image: "/projects/bungalows/amol-patil-row-house/01.jpg",
    images: [
      "/projects/bungalows/amol-patil-row-house/01.jpg",
      "/projects/bungalows/amol-patil-row-house/02.png",
      "/projects/bungalows/amol-patil-row-house/03.png",
    ],
    builtUp: "898 sqm",
    paragraphs: [
      "Amol Patil Row House occupies 898 sqm in Nashik, completed in 2023, built on the conviction that a family home should be understood before it is designed. The plan is organised around a clear geometry — rooms sequenced by use and privacy rather than by convention — giving the house an underlying order that is easy to live with. Natural light, material texture, and a restrained palette give the home its character, rather than ornament applied after the fact.",
      "The house is organised to be experienced gradually — arrival, threshold, gathering space, and private room — rather than taken in all at once. Like all our work, it is built on the belief that architecture should be inhabited, not merely occupied.",
    ],
  },
  {
    id: "37",
    slug: "nitin-sonawane-row-house",
    name: "Nitin Sonawane Row House",
    location: "Nashik, India",
    year: "2021",
    category: "Residential Bungalows",
    tags: ["Residential Bungalow", "Nashik"],
    color: "#b9c0b4",
    image: "/projects/bungalows/nitin-sonawane-row-house/01.jpg",
    images: [
      "/projects/bungalows/nitin-sonawane-row-house/01.jpg",
      "/projects/bungalows/nitin-sonawane-row-house/02.png",
      "/projects/bungalows/nitin-sonawane-row-house/03.png",
    ],
    builtUp: "357 sqm",
    paragraphs: [
      "Completed in 2021, Nitin Sonawane Row House is a 357 sqm house in Nashik that treats the brief — a family's daily life — as the real starting point of the design. Structure and proportion were resolved early, so the home's geometry stays legible even as it responds to the specific demands of its site. Openings, courtyards, and material transitions were considered for how they feel underfoot and overhead, not only how they read in a photograph.",
      "Every room was designed with a specific moment of the family's day in mind, from morning light in the kitchen to evening shade on the verandah. The result is a project that measures itself not only by how it looks, but by how it is lived in.",
    ],
  },
  {
    id: "38",
    slug: "shamkant-wagh",
    name: "Shamkant Wagh",
    location: "Nashik, India",
    year: "2025",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#bcc2c9",
    image: "/projects/interiors/shamkant-wagh/01.jpg",
    images: [
      "/projects/interiors/shamkant-wagh/01.jpg",
      "/projects/interiors/shamkant-wagh/02.jpg",
      "/projects/interiors/shamkant-wagh/03.jpg",
      "/projects/interiors/shamkant-wagh/04.jpg",
      "/projects/interiors/shamkant-wagh/05.jpg",
      "/projects/interiors/shamkant-wagh/06.jpg",
      "/projects/interiors/shamkant-wagh/07.jpg",
      "/projects/interiors/shamkant-wagh/08.jpg",
      "/projects/interiors/shamkant-wagh/09.jpg",
      "/projects/interiors/shamkant-wagh/10.jpg",
      "/projects/interiors/shamkant-wagh/11.jpg",
      "/projects/interiors/shamkant-wagh/12.jpg",
      "/projects/interiors/shamkant-wagh/13.jpg",
      "/projects/interiors/shamkant-wagh/14.png",
      "/projects/interiors/shamkant-wagh/15.png",
    ],
    paragraphs: [
      "Shamkant Wagh is an interior project in Nashik, completed in 2025, working within an existing shell to shape how it is used every day. Space planning came first — a clear organisation of use, movement, and privacy within the existing structure — before any material or finish was chosen. Texture, light, and a restrained material palette give the space its character, favouring quality of detail over decoration.",
      "The space was designed to support its daily use first, with atmosphere and character following from that clarity of purpose. Like all our work, it is built on the belief that architecture should be inhabited, not merely occupied.",
    ],
  },
  {
    id: "39",
    slug: "yoganand-ahire",
    name: "Yoganand Ahire",
    location: "Nashik, India",
    year: "2024",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#c9b9ae",
    image: "/projects/interiors/yoganand-ahire/01.jpg",
    images: [
      "/projects/interiors/yoganand-ahire/01.jpg",
      "/projects/interiors/yoganand-ahire/02.jpg",
      "/projects/interiors/yoganand-ahire/03.jpg",
      "/projects/interiors/yoganand-ahire/04.jpg",
      "/projects/interiors/yoganand-ahire/05.jpg",
      "/projects/interiors/yoganand-ahire/06.jpg",
      "/projects/interiors/yoganand-ahire/07.jpg",
      "/projects/interiors/yoganand-ahire/08.jpg",
      "/projects/interiors/yoganand-ahire/09.jpg",
      "/projects/interiors/yoganand-ahire/10.jpg",
      "/projects/interiors/yoganand-ahire/11.jpg",
      "/projects/interiors/yoganand-ahire/12.jpg",
      "/projects/interiors/yoganand-ahire/13.jpg",
      "/projects/interiors/yoganand-ahire/14.jpg",
      "/projects/interiors/yoganand-ahire/15.jpg",
      "/projects/interiors/yoganand-ahire/16.png",
      "/projects/interiors/yoganand-ahire/17.png",
    ],
    paragraphs: [
      "Completed in 2024 in Nashik, Yoganand Ahire reimagines an interior from within — space planning, material, and light resolved together rather than treated as separate decisions. The layout was resolved as a sequence of zones defined by use and light, giving the interior a legible order within its existing walls. Every finish and fixture was chosen for how it performs and feels over years of use, not just on the day of handover.",
      "Every zone was designed around the specific task or moment it needed to hold, so the interior functions as intended long after the finishes are chosen. The result is a project that measures itself not only by how it looks, but by how it is lived in.",
    ],
  },
  {
    id: "40",
    slug: "vinod-patil",
    name: "Vinod Patil",
    location: "Nashik, India",
    year: "2024",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#b8c7c9",
    image: "/projects/interiors/vinod-patil/01.jpg",
    images: [
      "/projects/interiors/vinod-patil/01.jpg",
      "/projects/interiors/vinod-patil/02.jpg",
      "/projects/interiors/vinod-patil/03.jpg",
      "/projects/interiors/vinod-patil/04.jpg",
      "/projects/interiors/vinod-patil/05.jpg",
      "/projects/interiors/vinod-patil/06.jpg",
      "/projects/interiors/vinod-patil/07.jpg",
      "/projects/interiors/vinod-patil/08.jpg",
      "/projects/interiors/vinod-patil/09.jpg",
      "/projects/interiors/vinod-patil/10.jpg",
      "/projects/interiors/vinod-patil/11.jpg",
      "/projects/interiors/vinod-patil/12.jpg",
      "/projects/interiors/vinod-patil/13.jpg",
      "/projects/interiors/vinod-patil/14.jpg",
      "/projects/interiors/vinod-patil/15.jpg",
      "/projects/interiors/vinod-patil/16.jpg",
      "/projects/interiors/vinod-patil/17.jpg",
      "/projects/interiors/vinod-patil/18.jpg",
      "/projects/interiors/vinod-patil/19.png",
    ],
    paragraphs: [
      "Vinod Patil, completed in 2024 in Nashik, is an interior project built on the belief that a space is defined as much by how it is inhabited as by how it is built. Circulation and zoning were treated as the project's real structure, with finishes layered on only once that underlying order was clear. Light fittings, material joins, and finish transitions were resolved with the same care as the plan itself, since an interior is judged at arm's length.",
      "The space is experienced as a sequence of moments — arrival, use, pause — rather than as a single composed view. For us, it is one more attempt to bring sense and sensibility into balance — structure with clarity, material with warmth.",
    ],
  },
  {
    id: "41",
    slug: "xtream-fitness",
    name: "Xtream Fitness",
    location: "Nashik, India",
    year: "2022",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#c2bcc9",
    image: "/projects/interiors/xtream-fitness/01.jpg",
    images: [
      "/projects/interiors/xtream-fitness/01.jpg",
      "/projects/interiors/xtream-fitness/02.jpg",
      "/projects/interiors/xtream-fitness/03.jpg",
      "/projects/interiors/xtream-fitness/04.jpg",
      "/projects/interiors/xtream-fitness/05.jpg",
      "/projects/interiors/xtream-fitness/06.jpg",
      "/projects/interiors/xtream-fitness/07.jpg",
      "/projects/interiors/xtream-fitness/08.jpg",
      "/projects/interiors/xtream-fitness/09.jpg",
      "/projects/interiors/xtream-fitness/10.jpg",
      "/projects/interiors/xtream-fitness/11.jpg",
      "/projects/interiors/xtream-fitness/12.png",
    ],
    paragraphs: [
      "In Nashik, Xtream Fitness — completed in 2022 — is an interior designed around the particular use it was built to serve. The plan was organised around use and flow first, so that every finish decision that followed had a clear spatial logic to sit within. A restrained material and lighting palette was chosen deliberately, so the space reads as considered rather than decorated.",
      "The result is a space organised around how it is actually used — movement, pause, and gathering — rather than around a fixed idea of how it should look. It stands as part of MJ Architects' ongoing exploration of how sense, sensibility, and space come together in the built environment.",
    ],
  },
  {
    id: "42",
    slug: "akshay-study-abroad",
    name: "Akshay Study Abroad",
    location: "Nashik, India",
    year: "2022",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#c9c4b6",
    image: "/projects/interiors/akshay-study-abroad/01.jpg",
    images: [
      "/projects/interiors/akshay-study-abroad/01.jpg",
      "/projects/interiors/akshay-study-abroad/02.jpg",
      "/projects/interiors/akshay-study-abroad/03.jpg",
      "/projects/interiors/akshay-study-abroad/04.jpg",
      "/projects/interiors/akshay-study-abroad/05.jpg",
      "/projects/interiors/akshay-study-abroad/06.jpg",
      "/projects/interiors/akshay-study-abroad/07.jpg",
      "/projects/interiors/akshay-study-abroad/08.jpg",
      "/projects/interiors/akshay-study-abroad/09.jpg",
      "/projects/interiors/akshay-study-abroad/10.jpg",
      "/projects/interiors/akshay-study-abroad/11.png",
    ],
    paragraphs: [
      "Akshay Study Abroad occupies an existing structure in Nashik, completed in 2022, reworked from within to suit the life and use it now holds. A disciplined layout — zones, circulation, and sightlines resolved early — gives the interior its order, independent of the finishes applied to it. Material, lighting, and detail were considered at close range — the scale at which an interior is actually experienced, day after day.",
      "Light, threshold, and material work together so the space is experienced as a sequence, not a single view. In the end, it is measured less by its elevation than by how naturally it has been taken up by the people who use it.",
    ],
  },
  {
    id: "43",
    slug: "ca-nilesh-gadhave",
    name: "CA Nilesh Gadhave",
    location: "Nashik, India",
    year: "2022",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#b9c0b4",
    image: "/projects/interiors/ca-nilesh-gadhave/01.jpg",
    images: [
      "/projects/interiors/ca-nilesh-gadhave/01.jpg",
      "/projects/interiors/ca-nilesh-gadhave/02.jpg",
      "/projects/interiors/ca-nilesh-gadhave/03.jpg",
      "/projects/interiors/ca-nilesh-gadhave/04.jpg",
      "/projects/interiors/ca-nilesh-gadhave/05.jpg",
      "/projects/interiors/ca-nilesh-gadhave/06.jpg",
      "/projects/interiors/ca-nilesh-gadhave/07.jpg",
      "/projects/interiors/ca-nilesh-gadhave/08.jpg",
      "/projects/interiors/ca-nilesh-gadhave/09.jpg",
      "/projects/interiors/ca-nilesh-gadhave/10.jpg",
      "/projects/interiors/ca-nilesh-gadhave/11.png",
    ],
    paragraphs: [
      "Completed in 2022, CA Nilesh Gadhave in Nashik takes an existing shell as its starting point, reworking it from within rather than beginning from a blank site. Space planning came first — a clear organisation of use, movement, and privacy within the existing structure — before any material or finish was chosen. Texture, light, and a restrained material palette give the space its character, favouring quality of detail over decoration.",
      "The space was designed to support its daily use first, with atmosphere and character following from that clarity of purpose. It reflects the studio's continuing pursuit of sense, sensibility, and space — order, depth, and life, brought together in one address.",
    ],
  },
  {
    id: "44",
    slug: "bhavsar-showroom",
    name: "Bhavsar Showroom",
    location: "Nashik, India",
    year: "2022",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#bcc2c9",
    image: "/projects/interiors/bhavsar-showroom/01.jpg",
    images: [
      "/projects/interiors/bhavsar-showroom/01.jpg",
      "/projects/interiors/bhavsar-showroom/02.jpg",
      "/projects/interiors/bhavsar-showroom/03.jpg",
      "/projects/interiors/bhavsar-showroom/04.png",
    ],
    paragraphs: [
      "Bhavsar Showroom, completed in 2022 in Nashik, treats the interior as its own design problem — distinct from, but disciplined by, the structure that contains it. The layout was resolved as a sequence of zones defined by use and light, giving the interior a legible order within its existing walls. Every finish and fixture was chosen for how it performs and feels over years of use, not just on the day of handover.",
      "Every zone was designed around the specific task or moment it needed to hold, so the interior functions as intended long after the finishes are chosen. Like all our work, it is built on the belief that architecture should be inhabited, not merely occupied.",
    ],
  },
  {
    id: "45",
    slug: "shriji-park-home",
    name: "Shriji Park Home",
    location: "Nashik, India",
    year: "2021",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#c9b9ae",
    image: "/projects/interiors/shriji-park-home/01.jpg",
    images: [
      "/projects/interiors/shriji-park-home/01.jpg",
      "/projects/interiors/shriji-park-home/02.jpg",
      "/projects/interiors/shriji-park-home/03.jpg",
      "/projects/interiors/shriji-park-home/04.jpg",
      "/projects/interiors/shriji-park-home/05.png",
      "/projects/interiors/shriji-park-home/06.png",
      "/projects/interiors/shriji-park-home/07.png",
    ],
    paragraphs: [
      "Shriji Park Home is an interior project in Nashik, completed in 2021, working within an existing shell to shape how it is used every day. Circulation and zoning were treated as the project's real structure, with finishes layered on only once that underlying order was clear. Light fittings, material joins, and finish transitions were resolved with the same care as the plan itself, since an interior is judged at arm's length.",
      "The space is experienced as a sequence of moments — arrival, use, pause — rather than as a single composed view. The result is a project that measures itself not only by how it looks, but by how it is lived in.",
    ],
  },
  {
    id: "46",
    slug: "sahebrao-waghere",
    name: "Sahebrao Waghere",
    location: "Nashik, India",
    year: "2021",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#b8c7c9",
    image: "/projects/interiors/sahebrao-waghere/01.jpg",
    images: [
      "/projects/interiors/sahebrao-waghere/01.jpg",
      "/projects/interiors/sahebrao-waghere/02.jpg",
      "/projects/interiors/sahebrao-waghere/03.png",
    ],
    paragraphs: [
      "Completed in 2021 in Nashik, Sahebrao Waghere reimagines an interior from within — space planning, material, and light resolved together rather than treated as separate decisions. The plan was organised around use and flow first, so that every finish decision that followed had a clear spatial logic to sit within. A restrained material and lighting palette was chosen deliberately, so the space reads as considered rather than decorated.",
      "The result is a space organised around how it is actually used — movement, pause, and gathering — rather than around a fixed idea of how it should look. For us, it is one more attempt to bring sense and sensibility into balance — structure with clarity, material with warmth.",
    ],
  },
  {
    id: "47",
    slug: "madhavbhai-patil",
    name: "Madhavbhai Patil",
    location: "Shahada, India",
    year: "2019",
    category: "Interiors",
    tags: ["Interior Design", "Shahada"],
    color: "#c2bcc9",
    image: "/projects/interiors/madhavbhai-patil/01.jpg",
    images: [
      "/projects/interiors/madhavbhai-patil/01.jpg",
      "/projects/interiors/madhavbhai-patil/02.jpg",
      "/projects/interiors/madhavbhai-patil/03.jpg",
      "/projects/interiors/madhavbhai-patil/04.jpg",
      "/projects/interiors/madhavbhai-patil/05.png",
    ],
    paragraphs: [
      "Madhavbhai Patil, completed in 2019 in Shahada, is an interior project built on the belief that a space is defined as much by how it is inhabited as by how it is built. A disciplined layout — zones, circulation, and sightlines resolved early — gives the interior its order, independent of the finishes applied to it. Material, lighting, and detail were considered at close range — the scale at which an interior is actually experienced, day after day.",
      "Light, threshold, and material work together so the space is experienced as a sequence, not a single view. It stands as part of MJ Architects' ongoing exploration of how sense, sensibility, and space come together in the built environment.",
    ],
  },
  {
    id: "48",
    slug: "mr-baviskar",
    name: "Mr. Baviskar",
    location: "Nashik, India",
    year: "2019",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#c9c4b6",
    image: "/projects/interiors/mr-baviskar/01.jpg",
    images: [
      "/projects/interiors/mr-baviskar/01.jpg",
      "/projects/interiors/mr-baviskar/02.jpg",
      "/projects/interiors/mr-baviskar/03.jpg",
      "/projects/interiors/mr-baviskar/04.jpg",
      "/projects/interiors/mr-baviskar/05.jpg",
      "/projects/interiors/mr-baviskar/06.jpg",
      "/projects/interiors/mr-baviskar/07.jpg",
      "/projects/interiors/mr-baviskar/08.png",
    ],
    paragraphs: [
      "In Nashik, Mr. Baviskar — completed in 2019 — is an interior designed around the particular use it was built to serve. Space planning came first — a clear organisation of use, movement, and privacy within the existing structure — before any material or finish was chosen. Texture, light, and a restrained material palette give the space its character, favouring quality of detail over decoration.",
      "The space was designed to support its daily use first, with atmosphere and character following from that clarity of purpose. In the end, it is measured less by its elevation than by how naturally it has been taken up by the people who use it.",
    ],
  },
  {
    id: "49",
    slug: "dr-vivek-patil",
    name: "Dr. Vivek Patil",
    location: "Nashik, India",
    year: "2019",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#b9c0b4",
    image: "/projects/interiors/dr-vivek-patil/01.jpg",
    images: [
      "/projects/interiors/dr-vivek-patil/01.jpg",
      "/projects/interiors/dr-vivek-patil/02.jpg",
      "/projects/interiors/dr-vivek-patil/03.jpg",
      "/projects/interiors/dr-vivek-patil/04.jpg",
      "/projects/interiors/dr-vivek-patil/05.jpg",
      "/projects/interiors/dr-vivek-patil/06.jpg",
      "/projects/interiors/dr-vivek-patil/07.jpg",
      "/projects/interiors/dr-vivek-patil/08.jpg",
      "/projects/interiors/dr-vivek-patil/09.png",
    ],
    paragraphs: [
      "Dr. Vivek Patil occupies an existing structure in Nashik, completed in 2019, reworked from within to suit the life and use it now holds. The layout was resolved as a sequence of zones defined by use and light, giving the interior a legible order within its existing walls. Every finish and fixture was chosen for how it performs and feels over years of use, not just on the day of handover.",
      "Every zone was designed around the specific task or moment it needed to hold, so the interior functions as intended long after the finishes are chosen. It reflects the studio's continuing pursuit of sense, sensibility, and space — order, depth, and life, brought together in one address.",
    ],
  },
  {
    id: "50",
    slug: "mahendra-patil",
    name: "Mahendra Patil",
    location: "Nashik, India",
    year: "2019",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#bcc2c9",
    image: "/projects/interiors/mahendra-patil/01.jpg",
    images: [
      "/projects/interiors/mahendra-patil/01.jpg",
      "/projects/interiors/mahendra-patil/02.jpg",
      "/projects/interiors/mahendra-patil/03.jpg",
      "/projects/interiors/mahendra-patil/04.png",
    ],
    paragraphs: [
      "Completed in 2019, Mahendra Patil in Nashik takes an existing shell as its starting point, reworking it from within rather than beginning from a blank site. Circulation and zoning were treated as the project's real structure, with finishes layered on only once that underlying order was clear. Light fittings, material joins, and finish transitions were resolved with the same care as the plan itself, since an interior is judged at arm's length.",
      "The space is experienced as a sequence of moments — arrival, use, pause — rather than as a single composed view. Like all our work, it is built on the belief that architecture should be inhabited, not merely occupied.",
    ],
  },
  {
    id: "51",
    slug: "sameer-patil",
    name: "Sameer Patil",
    location: "Nashik, India",
    year: "2018",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#c9b9ae",
    image: "/projects/interiors/sameer-patil/01.jpg",
    images: [
      "/projects/interiors/sameer-patil/01.jpg",
      "/projects/interiors/sameer-patil/02.jpg",
      "/projects/interiors/sameer-patil/03.jpg",
      "/projects/interiors/sameer-patil/04.jpg",
      "/projects/interiors/sameer-patil/05.jpg",
      "/projects/interiors/sameer-patil/06.jpg",
      "/projects/interiors/sameer-patil/07.jpg",
      "/projects/interiors/sameer-patil/08.jpg",
      "/projects/interiors/sameer-patil/09.jpg",
      "/projects/interiors/sameer-patil/10.jpg",
      "/projects/interiors/sameer-patil/11.jpg",
      "/projects/interiors/sameer-patil/12.png",
    ],
    paragraphs: [
      "Sameer Patil, completed in 2018 in Nashik, treats the interior as its own design problem — distinct from, but disciplined by, the structure that contains it. The plan was organised around use and flow first, so that every finish decision that followed had a clear spatial logic to sit within. A restrained material and lighting palette was chosen deliberately, so the space reads as considered rather than decorated.",
      "The result is a space organised around how it is actually used — movement, pause, and gathering — rather than around a fixed idea of how it should look. The result is a project that measures itself not only by how it looks, but by how it is lived in.",
    ],
  },
];

export function getProjectBySlug(slug: string) {
  return projects.find((p) => p.slug === slug);
}
