export type Project = {
  id: string;
  slug: string;
  name: string;
  location: string;
  year: string;
  category: "Industrial" | "Residential" | "Commercial" | "Healthcare" | "Institutional" | "Hospitality" | "Interiors";
  tags: string[];
  color: string;
  image?: string;
  images?: string[];
  builtUp?: string;
  description?: string;
  paragraphs?: string[];
};

export const projects: Project[] = [
  {
    id: "01",
    slug: "raj-crest",
    name: "Raj Crest",
    location: "Nashik, India",
    year: "2019",
    category: "Residential",
    tags: ["Apartment", "Nashik"],
    color: "#b9c0b4",
    image: "/projects/apartments/raj-crest/01.jpg",
    images: [
      "/projects/apartments/raj-crest/01.jpg",
      "/projects/apartments/raj-crest/02.jpg",
      "/projects/apartments/raj-crest/03.jpg",
      "/projects/apartments/raj-crest/04.png",
    ],
    builtUp: "13,355 sqm",
  },
  {
    id: "02",
    slug: "shankar-nagar",
    name: "Shankar Nagar",
    location: "Nashik, India",
    year: "2022",
    category: "Residential",
    tags: ["Apartment", "Nashik"],
    color: "#bcc2c9",
    image: "/projects/apartments/shankar-nagar/01.jpg",
    images: [
      "/projects/apartments/shankar-nagar/01.jpg",
      "/projects/apartments/shankar-nagar/02.jpg",
      "/projects/apartments/shankar-nagar/03.jpg",
      "/projects/apartments/shankar-nagar/04.jpg",
      "/projects/apartments/shankar-nagar/05.png",
      "/projects/apartments/shankar-nagar/06.png",
    ],
    builtUp: "27,599 sqm",
  },
  {
    id: "03",
    slug: "raj-tower",
    name: "Raj Tower",
    location: "Nashik, India",
    year: "2017",
    category: "Residential",
    tags: ["Apartment", "Nashik"],
    color: "#c9b9ae",
    image: "/projects/apartments/raj-tower/01.jpg",
    images: [
      "/projects/apartments/raj-tower/01.jpg",
      "/projects/apartments/raj-tower/02.jpg",
      "/projects/apartments/raj-tower/03.jpg",
      "/projects/apartments/raj-tower/04.png",
      "/projects/apartments/raj-tower/05.png",
    ],
    builtUp: "8,776 sqm",
  },
  {
    id: "04",
    slug: "ambar-arcade",
    name: "Ambar Arcade",
    location: "Nashik, India",
    year: "2026",
    category: "Residential",
    tags: ["Apartment", "Nashik"],
    color: "#b8c7c9",
    image: "/projects/apartments/ambar-arcade/01.jpg",
    images: [
      "/projects/apartments/ambar-arcade/01.jpg",
      "/projects/apartments/ambar-arcade/02.jpg",
      "/projects/apartments/ambar-arcade/03.png",
      "/projects/apartments/ambar-arcade/04.png",
    ],
    builtUp: "7,772 sqm",
  },
  {
    id: "05",
    slug: "pandav-enclave",
    name: "Pandav Enclave",
    location: "Nashik, India",
    year: "2021",
    category: "Residential",
    tags: ["Apartment", "Nashik"],
    color: "#c2bcc9",
    image: "/projects/apartments/pandav-enclave/01.jpg",
    images: [
      "/projects/apartments/pandav-enclave/01.jpg",
      "/projects/apartments/pandav-enclave/02.jpg",
      "/projects/apartments/pandav-enclave/03.jpg",
      "/projects/apartments/pandav-enclave/04.jpg",
      "/projects/apartments/pandav-enclave/05.png",
      "/projects/apartments/pandav-enclave/06.png",
    ],
    builtUp: "8,846 sqm",
  },
  {
    id: "06",
    slug: "prathmesh-park",
    name: "Prathmesh Park",
    location: "Nashik, India",
    year: "2019",
    category: "Residential",
    tags: ["Apartment", "Nashik"],
    color: "#c9c4b6",
    image: "/projects/apartments/prathmesh-park/01.jpg",
    images: [
      "/projects/apartments/prathmesh-park/01.jpg",
      "/projects/apartments/prathmesh-park/02.jpg",
      "/projects/apartments/prathmesh-park/03.jpg",
      "/projects/apartments/prathmesh-park/04.png",
      "/projects/apartments/prathmesh-park/05.png",
    ],
    builtUp: "7,977 sqm",
  },
  {
    id: "07",
    slug: "mhada-satpur",
    name: "Mhada Satpur",
    location: "Nashik, India",
    year: "2024",
    category: "Residential",
    tags: ["Apartment", "Nashik"],
    color: "#b9c0b4",
    image: "/projects/apartments/mhada-satpur/01.jpg",
    images: [
      "/projects/apartments/mhada-satpur/01.jpg",
      "/projects/apartments/mhada-satpur/02.jpg",
      "/projects/apartments/mhada-satpur/03.png",
      "/projects/apartments/mhada-satpur/04.png",
    ],
    builtUp: "4,953 sqm",
  },
  {
    id: "08",
    slug: "cosmos-chember",
    name: "Cosmos Chember",
    location: "Nashik, India",
    year: "2026",
    category: "Residential",
    tags: ["Apartment", "Nashik"],
    color: "#bcc2c9",
    image: "/projects/apartments/cosmos-chember/01.jpg",
    images: [
      "/projects/apartments/cosmos-chember/01.jpg",
      "/projects/apartments/cosmos-chember/02.png",
      "/projects/apartments/cosmos-chember/03.png",
    ],
    builtUp: "7,473 sqm",
  },
  {
    id: "09",
    slug: "vintage-valley",
    name: "Vintage Valley",
    location: "Igatpuri, India",
    year: "2024",
    category: "Residential",
    tags: ["Apartment", "Igatpuri"],
    color: "#c9b9ae",
    image: "/projects/apartments/vintage-valley/01.jpg",
    images: [
      "/projects/apartments/vintage-valley/01.jpg",
      "/projects/apartments/vintage-valley/02.jpg",
      "/projects/apartments/vintage-valley/03.png",
      "/projects/apartments/vintage-valley/04.png",
      "/projects/apartments/vintage-valley/05.png",
    ],
    builtUp: "6,985 sqm",
  },
  {
    id: "10",
    slug: "krishnai-galaxy",
    name: "Krishnai Galaxy",
    location: "Nashik, India",
    year: "2019",
    category: "Residential",
    tags: ["Apartment", "Nashik"],
    color: "#b8c7c9",
    image: "/projects/apartments/krishnai-galaxy/01.jpg",
    images: [
      "/projects/apartments/krishnai-galaxy/01.jpg",
      "/projects/apartments/krishnai-galaxy/02.jpg",
      "/projects/apartments/krishnai-galaxy/03.jpg",
      "/projects/apartments/krishnai-galaxy/04.png",
    ],
    builtUp: "3,847 sqm",
  },
  {
    id: "11",
    slug: "natures-pride",
    name: "Nature's Pride",
    location: "Nashik, India",
    year: "2024",
    category: "Residential",
    tags: ["Apartment", "Nashik"],
    color: "#c2bcc9",
    image: "/projects/apartments/natures-pride/01.jpg",
    images: [
      "/projects/apartments/natures-pride/01.jpg",
      "/projects/apartments/natures-pride/02.jpg",
      "/projects/apartments/natures-pride/03.png",
      "/projects/apartments/natures-pride/04.png",
    ],
    builtUp: "2,249 sqm",
  },
  {
    id: "12",
    slug: "indu-park",
    name: "Indu Park",
    location: "Nashik, India",
    year: "2026",
    category: "Residential",
    tags: ["Apartment", "Nashik"],
    color: "#c9c4b6",
    image: "/projects/apartments/indu-park/01.jpg",
    images: [
      "/projects/apartments/indu-park/01.jpg",
      "/projects/apartments/indu-park/02.png",
      "/projects/apartments/indu-park/03.png",
    ],
    builtUp: "2,175 sqm",
  },
  {
    id: "13",
    slug: "shri-ravi-enclave",
    name: "Shri Ravi Enclave",
    location: "Nashik, India",
    year: "2013",
    category: "Residential",
    tags: ["Apartment", "Nashik"],
    color: "#b9c0b4",
    image: "/projects/apartments/shri-ravi-enclave/01.jpg",
    images: [
      "/projects/apartments/shri-ravi-enclave/01.jpg",
      "/projects/apartments/shri-ravi-enclave/02.jpg",
      "/projects/apartments/shri-ravi-enclave/03.jpg",
      "/projects/apartments/shri-ravi-enclave/04.png",
    ],
    builtUp: "4,849 sqm",
  },
  {
    id: "14",
    slug: "aakar-beyond",
    name: "Aakar Beyond",
    location: "Nashik, India",
    year: "2018",
    category: "Residential",
    tags: ["Apartment", "Nashik"],
    color: "#bcc2c9",
    image: "/projects/apartments/aakar-beyond/01.jpg",
    images: [
      "/projects/apartments/aakar-beyond/01.jpg",
      "/projects/apartments/aakar-beyond/02.jpg",
      "/projects/apartments/aakar-beyond/03.jpg",
      "/projects/apartments/aakar-beyond/04.png",
      "/projects/apartments/aakar-beyond/05.png",
    ],
    builtUp: "2,481 sqm",
  },
  {
    id: "15",
    slug: "parkside-palms",
    name: "Parkside Palms",
    location: "Nashik, India",
    year: "2026",
    category: "Residential",
    tags: ["Apartment", "Nashik"],
    color: "#c9b9ae",
    image: "/projects/apartments/parkside-palms/01.jpg",
    images: [
      "/projects/apartments/parkside-palms/01.jpg",
      "/projects/apartments/parkside-palms/02.png",
      "/projects/apartments/parkside-palms/03.png",
    ],
    builtUp: "3,109 sqm",
  },
  {
    id: "16",
    slug: "paramkaruna-apartment",
    name: "Paramkaruna Apartment",
    location: "Nashik, India",
    year: "2026",
    category: "Residential",
    tags: ["Apartment", "Nashik"],
    color: "#b8c7c9",
    image: "/projects/apartments/paramkaruna-apartment/01.jpg",
    images: [
      "/projects/apartments/paramkaruna-apartment/01.jpg",
      "/projects/apartments/paramkaruna-apartment/02.png",
      "/projects/apartments/paramkaruna-apartment/03.png",
    ],
    builtUp: "1,051 sqm",
  },
  {
    id: "17",
    slug: "garden-view-apartment",
    name: "Garden View Apartment",
    location: "Nashik, India",
    year: "2025",
    category: "Residential",
    tags: ["Apartment", "Nashik"],
    color: "#c2bcc9",
    image: "/projects/apartments/garden-view-apartment/01.jpg",
    images: [
      "/projects/apartments/garden-view-apartment/01.jpg",
      "/projects/apartments/garden-view-apartment/02.jpg",
      "/projects/apartments/garden-view-apartment/03.png",
      "/projects/apartments/garden-view-apartment/04.png",
    ],
    builtUp: "1,065 sqm",
  },
  {
    id: "18",
    slug: "rukmini-park",
    name: "Rukmini Park",
    location: "Nashik, India",
    year: "2020",
    category: "Residential",
    tags: ["Apartment", "Nashik"],
    color: "#c9c4b6",
    image: "/projects/apartments/rukmini-park/01.jpg",
    images: [
      "/projects/apartments/rukmini-park/01.jpg",
      "/projects/apartments/rukmini-park/02.png",
      "/projects/apartments/rukmini-park/03.png",
    ],
    builtUp: "560 sqm",
  },
  {
    id: "19",
    slug: "shrishti-pandhari",
    name: "Shrishti Pandhari",
    location: "Pandharpur, India",
    year: "2015",
    category: "Residential",
    tags: ["Apartment", "Pandharpur"],
    color: "#b9c0b4",
    image: "/projects/apartments/shrishti-pandhari/01.jpg",
    images: [
      "/projects/apartments/shrishti-pandhari/01.jpg",
      "/projects/apartments/shrishti-pandhari/02.jpg",
      "/projects/apartments/shrishti-pandhari/03.jpg",
      "/projects/apartments/shrishti-pandhari/04.jpg",
      "/projects/apartments/shrishti-pandhari/05.jpg",
    ],
    builtUp: "7,432 sqm",
  },
  {
    id: "20",
    slug: "jay-shankar-bungalow",
    name: "Jay Shankar Bungalow",
    location: "Nashik, India",
    year: "2025",
    category: "Residential",
    tags: ["Residential Bungalow", "Nashik"],
    color: "#bcc2c9",
    builtUp: "394 sqm",
  },
  {
    id: "21",
    slug: "siddheshwar-walekar",
    name: "Siddheshwar Walekar",
    location: "Pimpalgaon, India",
    year: "2026",
    category: "Residential",
    tags: ["Residential Bungalow", "Pimpalgaon"],
    color: "#c9b9ae",
    builtUp: "681 sqm",
  },
  {
    id: "22",
    slug: "pravin-walekar",
    name: "Pravin Walekar",
    location: "Pimpalgaon, India",
    year: "2026",
    category: "Residential",
    tags: ["Residential Bungalow", "Pimpalgaon"],
    color: "#b8c7c9",
    builtUp: "734 sqm",
  },
  {
    id: "23",
    slug: "shyamji-soni-pipariya",
    name: "Shyamji Soni Pipariya",
    location: "Pipariya, Madhya Pradesh, India",
    year: "2021",
    category: "Residential",
    tags: ["Residential Bungalow", "Pipariya, Madhya Pradesh"],
    color: "#c2bcc9",
    builtUp: "1,100 sqm",
  },
  {
    id: "24",
    slug: "rahul-chaudhari",
    name: "Rahul Chaudhari",
    location: "Shahada, India",
    year: "2018",
    category: "Residential",
    tags: ["Residential Bungalow", "Shahada"],
    color: "#c9c4b6",
    builtUp: "246 sqm",
  },
  {
    id: "25",
    slug: "deepak-bodhale",
    name: "Deepak Bodhale",
    location: "Makhmalabad, Nashik, India",
    year: "2018",
    category: "Residential",
    tags: ["Residential Bungalow", "Makhmalabad, Nashik"],
    color: "#b9c0b4",
    builtUp: "349 sqm",
  },
  {
    id: "26",
    slug: "dr-avinash-chaudhari",
    name: "Dr. Avinash Chaudhari",
    location: "Shahada, India",
    year: "2020",
    category: "Residential",
    tags: ["Residential Bungalow", "Shahada"],
    color: "#bcc2c9",
    builtUp: "692 sqm",
  },
  {
    id: "27",
    slug: "sonawane-bungalow",
    name: "Sonawane Bungalow",
    location: "Taloda, Nandurbar, India",
    year: "2018",
    category: "Residential",
    tags: ["Residential Bungalow", "Taloda, Nandurbar"],
    color: "#c9b9ae",
    builtUp: "386 sqm",
  },
  {
    id: "28",
    slug: "dharmendra-patel",
    name: "Dharmendra Patel",
    location: "Shahada, India",
    year: "2019",
    category: "Residential",
    tags: ["Residential Bungalow", "Shahada"],
    color: "#b8c7c9",
    builtUp: "355 sqm",
  },
  {
    id: "29",
    slug: "ashok-bodke",
    name: "Ashok Bodke",
    location: "Pethroad, Nashik, India",
    year: "2016",
    category: "Residential",
    tags: ["Residential Bungalow", "Pethroad, Nashik"],
    color: "#c2bcc9",
    builtUp: "242 sqm",
  },
  {
    id: "30",
    slug: "dr-akshay-patil",
    name: "Dr. Akshay Patil",
    location: "Nashik, India",
    year: "2025",
    category: "Residential",
    tags: ["Residential Bungalow", "Nashik"],
    color: "#c9c4b6",
    builtUp: "161 sqm",
  },
  {
    id: "31",
    slug: "ajay-patil",
    name: "Ajay Patil",
    location: "Nashik, India",
    year: "2021",
    category: "Residential",
    tags: ["Residential Bungalow", "Nashik"],
    color: "#b9c0b4",
    builtUp: "168 sqm",
  },
  {
    id: "32",
    slug: "dr-chandrakant-patil",
    name: "Dr. Chandrakant Patil",
    location: "Shahada, India",
    year: "2020",
    category: "Residential",
    tags: ["Residential Bungalow", "Shahada"],
    color: "#bcc2c9",
    builtUp: "364 sqm",
  },
  {
    id: "33",
    slug: "dr-raj-khule",
    name: "Dr. Raj Khule",
    location: "Taloda, Nandurbar, India",
    year: "2018",
    category: "Residential",
    tags: ["Residential Bungalow", "Taloda, Nandurbar"],
    color: "#c9b9ae",
    builtUp: "260 sqm",
  },
  {
    id: "34",
    slug: "yashaswi-patil",
    name: "Yashaswi Patil",
    location: "Shahada, India",
    year: "2016",
    category: "Residential",
    tags: ["Residential Bungalow", "Shahada"],
    color: "#b8c7c9",
    builtUp: "223 sqm",
  },
  {
    id: "35",
    slug: "bhagwanbhai-chaudhari",
    name: "Bhagwanbhai Chaudhari",
    location: "Mahswad, Shahada, India",
    year: "2016",
    category: "Residential",
    tags: ["Residential Bungalow", "Mahswad, Shahada"],
    color: "#c2bcc9",
    builtUp: "268 sqm",
  },
  {
    id: "36",
    slug: "amol-patil-row-house",
    name: "Amol Patil Row House",
    location: "Nashik, India",
    year: "2023",
    category: "Residential",
    tags: ["Residential Bungalow", "Nashik"],
    color: "#c9c4b6",
    builtUp: "898 sqm",
  },
  {
    id: "37",
    slug: "nitin-sonawane-row-house",
    name: "Nitin Sonawane Row House",
    location: "Nashik, India",
    year: "2021",
    category: "Residential",
    tags: ["Residential Bungalow", "Nashik"],
    color: "#b9c0b4",
    builtUp: "357 sqm",
  },
  {
    id: "38",
    slug: "shamkant-wagh",
    name: "Shamkant Wagh",
    location: "Nashik, India",
    year: "2025",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#bcc2c9",
  },
  {
    id: "39",
    slug: "yoganand-ahire",
    name: "Yoganand Ahire",
    location: "Nashik, India",
    year: "2024",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#c9b9ae",
  },
  {
    id: "40",
    slug: "vinod-patil",
    name: "Vinod Patil",
    location: "Nashik, India",
    year: "2024",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#b8c7c9",
  },
  {
    id: "41",
    slug: "xtream-fitness",
    name: "Xtream Fitness",
    location: "Nashik, India",
    year: "2022",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#c2bcc9",
  },
  {
    id: "42",
    slug: "akshay-study-abroad",
    name: "Akshay Study Abroad",
    location: "Nashik, India",
    year: "2022",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#c9c4b6",
  },
  {
    id: "43",
    slug: "ca-nilesh-gadhave",
    name: "CA Nilesh Gadhave",
    location: "Nashik, India",
    year: "2022",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#b9c0b4",
  },
  {
    id: "44",
    slug: "bhavsar-showroom",
    name: "Bhavsar Showroom",
    location: "Nashik, India",
    year: "2022",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#bcc2c9",
  },
  {
    id: "45",
    slug: "shriji-park-home",
    name: "Shriji Park Home",
    location: "Nashik, India",
    year: "2021",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#c9b9ae",
  },
  {
    id: "46",
    slug: "sahebrao-waghere",
    name: "Sahebrao Waghere",
    location: "Nashik, India",
    year: "2021",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#b8c7c9",
  },
  {
    id: "47",
    slug: "madhavbhai-patil",
    name: "Madhavbhai Patil",
    location: "Shahada, India",
    year: "2019",
    category: "Interiors",
    tags: ["Interior Design", "Shahada"],
    color: "#c2bcc9",
  },
  {
    id: "48",
    slug: "mr-baviskar",
    name: "Mr. Baviskar",
    location: "Nashik, India",
    year: "2019",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#c9c4b6",
  },
  {
    id: "49",
    slug: "dr-vivek-patil",
    name: "Dr. Vivek Patil",
    location: "Nashik, India",
    year: "2019",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#b9c0b4",
  },
  {
    id: "50",
    slug: "mahendra-patil",
    name: "Mahendra Patil",
    location: "Nashik, India",
    year: "2019",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#bcc2c9",
  },
  {
    id: "51",
    slug: "sameer-patil",
    name: "Sameer Patil",
    location: "Nashik, India",
    year: "2018",
    category: "Interiors",
    tags: ["Interior Design", "Nashik"],
    color: "#c9b9ae",
  },
];

export function getProjectBySlug(slug: string) {
  return projects.find((p) => p.slug === slug);
}
